AspNetVS2017.Captiulo03.PortFolio/Models/ContatoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetVS2017.Captiulo03.PortFolio.Models
{
    public class ContatoViewModel
    {
        public int Id { get; set; }

        [Required]
        public string Nome { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        public string Mensagem { get; set; }
    }
}

AspNetVS2017.Captiulo03.PortFolio/Models/PortfolioViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AspNetVS2017.Captiulo03.PortFolio.Models
{
    public class PortfolioViewModel
    {
        public List<string> CaminhosImagens { get; set; } = new List<string>();
    }
}

AspNetVS2017.Captiulo03.PortFolio/Controllers/HomeController.cs
using AspNetVS2017.Captiulo03.PortFolio.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AspNetVS2017.Captiulo03.PortFolio.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "JBS.";

            return View();
        }

        [HttpGet]
        public ActionResult Contact()
        {
            ViewBag.Mensagem = "Entre em contato";

            return View();
        }

        [HttpPost]
        public ActionResult Contact(ContatoViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            var stringConexao = ConfigurationManager.ConnectionStrings["portfolioSqlServer"].ConnectionString;

            using (var conexao = new SqlConnection(stringConexao))
            {
                conexao.Open();

                const string instrucao = @"
                                INSERT INTO[dbo].[Contato]
                                          ([Nome]
                                          ,[Email]
                                          ,[Mensagem])
                                    VALUES(@Nome               
                                          ,@Email               
                                          ,@Mensagem)
                                 ";
                using (var comando = new SqlCommand(instrucao, conexao))
                {
                    comando.Parameters.AddWithValue("@Nome", viewModel.Nome);
                    comando.Parameters.AddWithValue("@Email", viewModel.Email);
                    comando.Parameters.AddWithValue("@Mensagem", viewModel.Mensagem);

                    comando.ExecuteNonQuery();
                }

                //conexao.Close(); não precisa;
            }

            ModelState.Clear();

            return View();
        }
    }
}

AspNetVS2017.Captiulo03.PortFolio/Controllers/PortfolioController.cs
using AspNetVS2017.Captiulo03.PortFolio.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AspNetVS2017.Captiulo03.PortFolio.Controllers
{
    public class PortfolioController : Controller
    {
        // GET: Portfolio
        public ActionResult Index()
        {
            const string diretorioImagens = "/Content/Imagens/Portfolio";
            var caminhos = Directory
                .EnumerateFiles(Server.MapPath(diretorioImagens));

            var viewModel = new PortfolioViewModel();
            
            foreach (var caminho in caminhos)
            {
                viewModel.CaminhosImagens.Add($"{diretorioImagens}/{Path.GetFileName(caminho)}");
            }

            return View(viewModel);
        }
    }
}

AspNetVS2017.Captiulo03.PortFolio/Views/Home/Contact.cshtml
@model AspNetVS2017.Captiulo03.PortFolio.Models.ContatoViewModel

@{
    ViewBag.Title = "Contact";
}

<h2>Contact</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@ViewBag.Mensagem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mensagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Mensagem, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Mensagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AspNetVS2017.Captiulo03.PortFolio/Views/Portfolio/Index.cshtml
@model AspNetVS2017.Captiulo03.PortFolio.Models.PortfolioViewModel

@{
    ViewBag.Title = "Portfólio";
}
@section css{
    <link href="~/Content/jquery.fancybox.css" rel="stylesheet" />
}
<h2>Portfólio</h2>
<div class="row">
    @foreach (var caminho in Model.CaminhosImagens)
    {
        <a href="@caminho" class="fancybox">
            <img src="@caminho" alt="@caminho" class="img-responsive"/>
        </a>
    }
</div>
@section scripts{
    <script src="~/Scripts/jquery.fancybox.js"></script>
    <script type="text/javascript">
        //var elemento = document.getElementById("mensagemErro")
        $(".fancybox").fancybox();
    </script>
}

AspNetVS2017.Captiulo03.PortFolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @RenderSection("css", required: false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Portfólio", "Index", "Portfolio")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>